meal_prep_app/urls.py
from django.urls import path
from . import views

app_name = 'meal_prep_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('recipes', views.all_recipes, name='recipes'),
    path('recipes/<int:recipe_pk>', views.detail, name='detail'),
    path('recipes/new_recipe', views.new_recipe, name='new_recipe'),
    path('recipes/edit_recipe/<int:recipe_pk>', views.edit_recipe, name='edit_recipe'),
    path('recipes/user_recipes/', views.user_recipes, name="user_recipes"),
    path('choose_recipe', views.choose_recipe, name="choose_recipe"),
    path('user_recipe_lists', views.user_recipe_lists, name='user_lists'),
    path('recipe_list/<int:list_pk>', views.recipe_list, name='recipe_list'),
    path('user_recipe_lists/new_recipe_list', views.new_recipe_list, name='new_recipe_list'),
    path('user_recipe_lists/add_recipe/<int:recipe_pk>', views.add_recipe_to_user_list, name='add_recipe_to_user_list'),
    path('create_shopping_list/<int:list_pk>', views.create_shopping_list, name='create_shopping_list'),
]

# path('edit_shopping_list/<int:list_pk>', views.edit_shopping_list, name="edit_shopping_list"),

meal_prep_project/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', include('meal_prep_app.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('__debug__/', include(debug_toolbar.urls)),
]

meal_prep_app/models.py
from django.db import models
from datetime import timedelta
from django.contrib.auth.models import User
# Create your models here.

UNITS = [
        ('', ''),
        ('g', 'g'),
        ('kg', 'kg'),
        ('l', 'l'),
        ('ml', 'ml'),
        ('szklanka', 'szklanka'),
        ('łyżka', 'łyżka'),
        ('łyżeczka', 'łyżeczka'),
        ('ząbek', 'ząbek'),
        ('szczypta', 'szczypta')
    ]


class Recipe(models.Model):
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200, blank=False, unique=True, null=False)
    pub_date = models.DateField(blank=False)
    preparation_time = models.DurationField(default=timedelta(hours=1))
    people = models.PositiveSmallIntegerField(default=2)
    # img1 = models.ImageField()
    description = models.TextField()
    # img2 = models.ImageField()
    # img3 = models.ImageField()
    recipe = models.TextField(blank=False, default="Przykładowy przepis:"
                                                   "\n1. Przygotuj składniki"
                                                   "\n2. Wymieszaj"
                                                   "\n3. Gotowe!")

    def __str__(self):
        return f"{self.title}"


class Ingredient(models.Model):

    name = models.CharField(max_length=30, blank=False, null=False, unique=True, help_text="Name of the ingredient")

    def __str__(self):
        return f"{self.name}"


class Amount(models.Model):
    # DO NOT CHANGE THE ORDER OF THE LIST!!!
    # new tuples add on the bottom of the list
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='amounts')
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, related_name='ingredient_pk', null=True)
    amount = models.FloatField(default=0.0, help_text='Amount of ingredient', blank=False)
    unit = models.CharField(max_length=15, choices=UNITS, blank=True, default='')
    short_description = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return f"{self.amount} {self.unit} {self.ingredient}"


class RecipeList(models.Model):
    title = models.CharField(max_length=30, blank=False, null=False, default="")
    user = models.ManyToManyField(User)
    recipes = models.ManyToManyField(Recipe, related_name='recipe_lists')

    def __str__(self):
        return f"{self.title}"


class ShoppingList(models.Model):
    title = models.CharField(max_length=50, blank=False, null=False, default="")
    user = models.ManyToManyField(User, related_name='shopping_lists')
    # amounts = models.ManyToManyField(Amount, blank=True)
    # recipes = models.ManyToManyField(Recipe, blank=True)
    recipe_lists = models.ManyToManyField(RecipeList, blank=True, related_name='shopping_lists')
    # recipe_list = models.OneToOneField(RecipeList, on_delete=models.CASCADE, blank=False, primary_key=True,
    #                                    related_name='shopping_list', default=RecipeList.objects.get(pk=0))

    def __str__(self):
        return f"{self.title}"


class Item(models.Model):
    shopping_list = models.ForeignKey(ShoppingList, on_delete=models.CASCADE)
    checked = models.BooleanField(default=False)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, null=True)
    amount = models.FloatField(default=0.0, help_text='Amount of ingredient', blank=False)
    unit = models.CharField(max_length=15, choices=UNITS, blank=True, default='')

    def __str__(self):
        return f"{self.amount} {self.unit} {self.ingredient}"

meal_prep_app/forms.py
from django.forms import ModelForm
from .models import Recipe, Amount, Ingredient, RecipeList, ShoppingList, Item


class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'title', 'pub_date', 'preparation_time', 'people', 'description', 'recipe']


class AmountForm(ModelForm):
    class Meta:
        model = Amount
        fields = ['ingredient', 'amount', 'unit', 'short_description']
        # extra = 1


class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ['ingredient', 'amount', 'unit']


class IngredientForm(ModelForm):
    class Meta:
        model = Ingredient
        fields = '__all__'


class RecipeListForm(ModelForm):
    class Meta:
        model = RecipeList
        fields = ['title', 'recipes']


class ShoppingListForm(ModelForm):
    class Meta:
        model = ShoppingList
        fields = ['title', 'recipe_lists']

meal_prep_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Recipe, Ingredient, Amount, RecipeList, ShoppingList, Item
from .forms import RecipeForm, AmountForm, IngredientForm, RecipeListForm, ShoppingListForm, ItemForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import datetime
from .utils import *


def home(req):
    return render(req, 'meal_prep_app/home.html')


def all_recipes(req):
    show_req_post(req)
    recipes = Recipe.objects.all()

    res = {
        'recipes': recipes,
    }
    return render(req, 'meal_prep_app/all_recipes.html', context=res)


def detail(req, recipe_pk):
    show_req_post(req)
    recipe = get_object_or_404(Recipe, pk=recipe_pk)
    recipe = combine_details_about_recipe(recipe)
    if req.method == 'POST':
        if 'info' in req.POST:
            info = [f"Tytuł: {recipe.title}", f"Autor: {recipe.author.username}"]
            return show_info(req, info)
    context = {
        'recipe': recipe,
        'request_username': req.user.username,
    }
    return render(req, template_name='meal_prep_app/detail.html', context=context)


@login_required
def user_recipe_lists(req):
    return render(req, 'meal_prep_app/user_lists.html', context={'user_lists': get_user_recipe_lists(req)})


@login_required
def recipe_list(req, list_pk):
    show_req_post(req)
    list_of_recipes = get_object_or_404(RecipeList, pk=list_pk)
    if req.method == 'POST':
        if "recipe_to_remove" in req.POST:
            recipe_to_remove = get_object_or_404(Recipe, pk=req.POST["recipe_to_remove"])
            list_of_recipes.recipes.remove(recipe_to_remove)

        if 'chosen_recipe_pk' in req.POST:
            recipe = get_object_or_404(Recipe, pk=req.POST['chosen_recipe_pk'])
            list_of_recipes.recipes.add(recipe)

        if 'add_recipe' in req.POST:
            return choose_recipe(req)

        if 'create_shopping_list' in req.POST:
            # user clicked "shopping list"
            shopping_list = ShoppingList()
            shopping_list.title = f"Lista zakupów: {list_of_recipes.title}"
            shopping_list.save()
            shopping_list.user.add(req.user)
            shopping_list.recipe_lists.add(list_of_recipes)
            return redirect('meal_prep_app:create_shopping_list', shopping_list.pk)

    recipes = list_of_recipes.recipes.all()
    for recipe in recipes:
        choice = Choice("recipe_to_remove", recipe.pk, "Usuń z listy")
        recipe.choice = choice

    res = {
        "list_name": list_of_recipes.title,
        "list_of_recipes": recipes,
    }
    return render(req, template_name='meal_prep_app/list_of_recipes.html', context=res)


@login_required
def new_recipe(req):
    show_req_post(req)
    recipe_form = RecipeForm()

    if req.method == 'POST':
        # recipe_form.title.validate()
        recipe = recipe_form.save(commit=False)
        recipe.author = req.user
        recipe.title = req.POST['title']
        recipe.pub_date = datetime.date.today()
        recipe.preparation_time = datetime.timedelta(hours=1)
        recipe.recipe = "Przykładowy przepis:\n1. Przygotuj składniki\n2. Wymieszaj\n3. Gotowe!"
        recipe.people = 2
        recipe.description = ""
        recipe.save()
        return redirect('meal_prep_app:edit_recipe', recipe.pk)

    res = {
        'new_recipe_form': recipe_form,
    }
    return render(req, 'meal_prep_app/new_recipe.html', context=res)


@login_required
def edit_recipe(req, recipe_pk):
    show_req_post(req)

    recipe = get_object_or_404(Recipe, pk=recipe_pk)
    if recipe.author != req.user:
        return show_info(req, ["To nie twój przepis!", "Nie możesz go edytować."])

    amounts = Amount.objects.filter(recipe=recipe)
    form = RecipeForm(req.POST or None, req.FILES or None, instance=recipe)
    amount_form = AmountForm()
    delete_question = f"Czy na pewno chesz usunąć ten przepis? {recipe.title}"
    if req.method == 'POST':
        if 'ingredient' in req.POST:
            # adding new amount of ingredient
            amount_form = AmountForm(req.POST)
            if amount_form.is_valid():
                amount = amount_form.save(commit=False)
                amount.recipe = recipe
                amount.save()
                # when submit in form, the data in other forms is not in req.POST dict
                form = RecipeForm(instance=recipe)
                amount_form = AmountForm()

        if 'title' in req.POST:
            if form.is_valid():
                recipe = form.save(commit=False)
                recipe.save()
                return redirect('meal_prep_app:recipes')

        if 'delete_recipe' in req.POST:
            # user clicked delete button
            return ask_yes_or_no_question(req, delete_question)

        if delete_question in req.POST:
            if req.POST[delete_question] == "Yes":
                # user confirmed deleting recipe
                recipe.delete()
                return redirect('meal_prep_app:recipes')

    is_recipe_new = not form.is_valid()
    print(is_recipe_new)

    res = {
        'edit_recipe_form': form,
        'amount_form': amount_form,
        'amounts': amounts,
        'is_recipe_new': is_recipe_new,
    }

    return render(req, 'meal_prep_app/edit_recipe.html', context=res)


@login_required
def user_recipes(req):
    recipes = Recipe.objects.filter(author=req.user.pk)
    res = {
        'recipes': recipes,
    }
    return render(req, template_name="meal_prep_app/user_recipes.html", context=res)


@login_required
def new_recipe_list(req):
    recipe_list_form = RecipeListForm(req.POST or None, req.FILES or None)
    if req.method == 'POST':
        if recipe_list_form.is_valid():
            recipe_list = recipe_list_form.save()
            recipe_list.user.add(req.user)
            return redirect('meal_prep_app:user_lists')
    res = {
        'recipe_list_form': recipe_list_form,
    }
    return render(req, template_name='meal_prep_app/new_recipe_list.html', context=res)


@login_required
def add_recipe_to_user_list(req, recipe_pk):
    show_req_post(req)
    recipe = get_object_or_404(Recipe, pk=recipe_pk)
    user_lists = get_user_recipe_lists(req)

    if req.method == 'POST':
        if 'chosen_recipe_list_pk' in req.POST:
            # user clicked one of his/her recipe list
            chosen_recipe_list = get_object_or_404(RecipeList, pk=req.POST['chosen_recipe_list_pk'])
            chosen_recipe_list.recipes.add(recipe)
            return redirect('meal_prep_app:recipe_list', req.POST['chosen_recipe_list_pk'])

        if 'Anuluj' in req.POST:
            return redirect('meal_prep_app:detail', recipe.pk)

    choices = []
    for u_list in user_lists:
        choice = Choice("chosen_recipe_list_pk", u_list.pk, u_list.title)
        choices.append(choice)

    question = f"Wybierz listę, do której dodać {recipe.title}"
    res = {
        'question': question,
        'choices': choices,
        'target_url': "",
    }
    return render(req, template_name='meal_prep_app/choice_template.html', context=res)


@login_required
def create_shopping_list(req, list_pk):
    show_req_post(req)
    shopping_list = ShoppingList.objects.prefetch_related('recipe_lists').get(pk=list_pk)
    recipe_lists = list(RecipeList.objects.filter(shopping_lists=list_pk))
    print(recipe_lists)
    recipes = [get_recipes_from_recipe_list(r_list) for r_list in shopping_list.recipe_lists.all()]
    print(recipes)
    # items += recipe_items
    item_form = ItemForm(req.POST or None)

    if req.method == 'POST':
        if 'add_item' in req.POST:
            item = item_form.save(commit=False)
            item.shopping_list = shopping_list
            item.save()
            item_form = ItemForm()

    items = list(Item.objects.filter(shopping_list=shopping_list))

    res = {
        # 'recipes': recipes,
        'items': items,
        'item_form': item_form,
    }
    return render(req, template_name='meal_prep_app/new_shopping_list.html', context=res)


# def edit_shopping_list(req, list_pk):
#     shopping_list = get_object_or_404(ShoppingList, pk=list_pk)
#     recipe_lists = shopping_list.recipe_lists.all()
#     recipes = shopping_list.recipes.all()
#     amounts = shopping_list.amounts.all()
#     # for recipe_list in recipe_lists:
#     #     recipes += recipe_list.recipes.all()
#     #
#     # for recipe in recipes:
#     #     amounts += Amount.objects.filter(recipe=recipe)
#     res = {
#         'recipe_lists': recipe_lists,
#         'recipes': recipes,
#         'amounts': amounts,
#     }
#     return render(req, template_name='meal_prep_app/edit_shopping_list.html', context=res)

meal_prep_app/templates/meal_prep_app/all_recipes.html
{% extends 'meal_prep_app/main.html' %}
{% load pluralize_pl %}
{% block title %}Wszystkie przepisy{% endblock %}
{% block body %}

<a href="{% url 'meal_prep_app:home' %}">Wróć</a>

    {% for recipe in recipes %}
        <a href="{% url 'meal_prep_app:detail' recipe.pk %}"><h1>{{ recipe.title }}</h1></a>
        <h2>{{ recipe.pub_date|date:"Y.m.d" }}</h2>
        <h4>{{ recipe.description|linebreaks }}</h4>
        <br>
        {% endfor %}

{% endblock %}

meal_prep_app/templates/meal_prep_app/choice_template.html
{% extends 'meal_prep_app/main.html' %}
{% block title %}{% endblock %}
{% block body %}
<form method="post" action="{{ target_url }}">
    {{ question }}
    {% csrf_token %}
    {% for choice in choices %}
        <li>
            <button type="submit" name="{{choice.name}}" value="{{choice.value}}">{{choice.text}}</button>
        </li>
        {% endfor %}
    <button type="submit" name="Anuluj" value="Cancel">Anuluj</button>
</form>
{% endblock %}

meal_prep_app/templates/meal_prep_app/detail.html
{% extends 'meal_prep_app/main.html' %}
{% load pluralize_pl %}
{% block title %}{{ recipe.title }}{% endblock %}
{% block body %}
    <a href="{% url 'meal_prep_app:recipes' %}">Wróć</a>
    <h1>{{ recipe.title }}</h1>
        <h2>{{ recipe.pub_date|date:"Y.m.d" }}</h2>
        <h4>{{ recipe.description|linebreaks }}</h4>
        <h4>Składniki dla {{ recipe.people }} {{ recipe.people|pluralize_pl:"osoby, osób" }}:</h4>
        <ul>
            <table style="width:25%">
                {% for amount in recipe.list_of_amounts %}
                    <tr>
                        <td><h5>{{ amount.ingredient }}</h5></td>
                        <td><h5>{{ amount.amount }}</h5></td>
                        <td><h5>{{ amount.unit }}</h5></td>
                    </tr>
                    {% endfor %}
            </table>
        </ul>
        <h3>Przepis:</h3>
        <ul><h4>{{ recipe.recipe|linebreaks }}</h4></ul>
<form method="post" action="">{%csrf_token%}<button type="submit" name="info">Informacje</button></form>
{% if recipe.author.username == request_username %}
    <a href="{% url 'meal_prep_app:edit_recipe' recipe.pk %}"><button type="button">Edytuj przepis</button></a>
    {% endif %}

{% if user.is_authenticated %}
    <a href="{% url 'meal_prep_app:add_recipe_to_user_list' recipe.pk %}"><button type="button">Dodaj do mojej listy przepisów</button></a>
    {% endif %}

{% endblock %}

meal_prep_app/templates/meal_prep_app/edit_recipe.html
{% extends 'meal_prep_app/main.html' %}
{% block title %}Edytuj przepis{% endblock %}
{% block body %}
<p>{{is_recip_new}}</p>
{% if is_recipe_new %}
<h1>Dokończ tworzyć przepis</h1>
{% else %}
<h1>Edytuj przepis</h1>
{% endif %}
<form method="post" action="">
    {% csrf_token %}
    <button type="submit" name="delete_recipe" value="Yes">Usuń przepis</button>
</form>
<h2>Składniki:</h2>
{% for amount in amounts %}
    <p>{{ amount }}</p>
    {% endfor %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h3>Dodaj nowy składnik</h3>
    {{ amount_form.as_p }}
    <button type="submit">Dodaj</button>
</form>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h3>Przepis</h3>
    {{ edit_recipe_form.as_p }}
    <button type="submit">Zapisz</button>
    <a href="{% url 'meal_prep_app:recipes' %}">Anuluj</a>
</form>
{% endblock %}

meal_prep_app/templates/meal_prep_app/home.html
{% extends 'meal_prep_app/main.html' %}
{% load pluralize_pl %}
{% block title %}Home{% endblock %}
{% block body %}

<h1>Hello!</h1>

<ul>
    <li><a href="{% url 'meal_prep_app:recipes' %}">Wszystkie przepisy</a></li>
    <li><a href="{% url 'meal_prep_app:user_lists' %}">Moje listy przepisów</a></li>
</ul>


{% endblock %}

meal_prep_app/templates/meal_prep_app/info_template.html
{% extends 'meal_prep_app/main.html' %}
{% block title %}{% endblock %}
{% block body %}
<form method="post" action="{{ target_url }}">
    {% for i in info %}
        <p>{{ i }}</p>
        {% endfor %}
    {% csrf_token %}
    <button type="submit" name="{{ info }}" value="Ok">Ok</button>
</form>
{% endblock %}

meal_prep_app/templates/meal_prep_app/list_of_recipes.html
{% extends 'meal_prep_app/main.html' %}
{% block title %}Lista przepisów{% endblock %}
{% block body %}
<h1>
    {{ list_name }}
    <form method="post" action="">
        {% csrf_token %}
        <button type="submit" name="create_shopping_list">Lista zakupów</button>
    </form>
</h1>
<ul>
    {% for recipe in list_of_recipes %}
        <li>

            <form method="post" action="{{target_url}}">
                <a href="{% url 'meal_prep_app:detail' recipe.pk %}">{{recipe.title}}</a>
                {% csrf_token %}
                <button type="submit" name="{{recipe.choice.name}}" value="{{recipe.choice.value}}">{{recipe.choice.text}}</button>
            </form>
        </li>
        {% endfor %}
    <li>
        <form action="" method="post">
            {%csrf_token%}
            <button type="submit" name="add_recipe" value="True">Dodaj przepis do listy</button>
        </form>
    </li>
</ul>
{% endblock %}

<a href="{% url 'meal_prep_app:choose_recipe' %}">
    {% csrf_token %}
    <button type="button">Dodaj przepis do listy</button>
</a>

meal_prep_app/templates/meal_prep_app/main.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <script src="https://use.fontawesome.com/7cf433b332.js"></script>
</head>
<body>
    <a href="{% url 'meal_prep_app:home' %}"><button type="button">Strona główna</button></a>
    <a href="{% url 'meal_prep_app:user_lists' %}"><button type="button">Moje listy przepisów</button></a>
    <a href="{% url 'meal_prep_app:user_recipes' %}"><button type="button">Moje przepisy</button></a>
    <a href="{% url 'meal_prep_app:new_recipe' %}"><button type="button">Stwórz przepis</button></a>
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}"><button type="button">Wyloguj: {{user.username}}</button></a>
        {% else %}
        <a href="{% url 'login' %}"><button type="button">Zaloguj</button></a>
        {% endif %}
    <hr>
    <br>
    {% block body %}{% endblock %}
</body>
</html>

meal_prep_app/templates/meal_prep_app/new_recipe.html
{% extends 'meal_prep_app/main.html' %}
{% block title %}Nowy przepis{% endblock %}
{% block body %}
<form method="post" name="Przepis">
    {% csrf_token %}
    <h5>Tytuł przepisu</h5>
    {{ new_recipe_form.title }}
    <button type="submit">Zapisz przepis</button>
    <a href="{% url 'meal_prep_app:recipes' %}">Anuluj</a>
</form>

{% endblock %}

meal_prep_app/templates/meal_prep_app/new_recipe_list.html
{% extends 'meal_prep_app/main.html' %}
{% block title %}Nowa list przepisów{% endblock %}
{% block body %}
<form method="post" name="Lista przepisow">
    {% csrf_token %}
    {{ recipe_list_form }}
    <button type="submit">Zapisz listę</button>
    <a href="{% url 'meal_prep_app:recipes' %}">Anuluj</a>
</form>

{% endblock %}

meal_prep_app/templates/meal_prep_app/new_shopping_list.html
{% extends 'meal_prep_app/main.html' %}
{% block title %}Nowa lista zakupów{% endblock %}
{% block body %}

<!--{% for recipe_list in recipe_lists %}-->
<!--<p>{{ recipe_list }}</p>-->
<!--{% endfor %}-->
<!--{% for recipe in recipes %}-->
<!--<p>{{ recipe }}</p>-->
<!--{% endfor %}-->
<h2>Składniki do kupienia</h2>
{% for item in items %}
<p><input type="checkbox" value={{ item.checked }}></input>{{ item }}</p>
{% endfor %}
<form method="post" action="">
    {% csrf_token %}
    <p>{{ item_form }}</p>
    <button type="submit" name="add_item">Dodaj do listy</button>
    <a href="{% url 'meal_prep_app:recipes' %}"><button type="button">Anuluj</button></a>
</form>

{% endblock %}

meal_prep_app/templates/meal_prep_app/question_template.html
{% extends 'meal_prep_app/main.html' %}
{% block title %}{% endblock %}
{% block body %}
<form method="post" action="{{ target_url }}">
    {{ question }}
    {% csrf_token %}
    <button type="submit" name="{{ question }}" value="Yes">Tak</button>
    <button type="submit" name="{{ question }}" value="No">Nie</button>
</form>
{% endblock %}

meal_prep_app/templates/meal_prep_app/user_lists.html
{% extends 'meal_prep_app/main.html' %}
{% block title %}Zapisane listy przepisów{% endblock%}
{% block body %}
<h1>Moje listy przepisów</h1>
<ul>
    {% for list in user_lists %}
        <li><a href="{% url 'meal_prep_app:recipe_list' list.pk %}">{{ list.title }}</a></li>
        {%endfor%}
    <li>
        <a href="{% url 'meal_prep_app:new_recipe_list' %}"><button type="button">Nowa lista przepisów</button></a>
    </li>
</ul>
{% endblock %}

meal_prep_app/templates/meal_prep_app/user_recipes.html
{% extends 'meal_prep_app/main.html' %}
{% block title %}Moje przepisy{% endblock%}
{% block body %}
<h1>Moje przepisy</h1>
<ul>
    {% for recipe in recipes %}
        <li><a href="{% url 'meal_prep_app:detail' recipe.pk %}">{{ recipe.title }}</a></li>
        {%endfor%}
    <li>
        <a href="{% url 'meal_prep_app:new_recipe' %}"><button type="button">Stwórz przepis</button></a>
    </li>
</ul>
{% endblock %}